### ISSUE TITLE
"npm install node@lts" reports 12.18.1 which does not match 12.18.2 listed on website

### ISSUE THREAD

**Issue by mlandisbqs** [aredridel/node-bin-gen#103]
* **Version**: v12.18.1
* **Platform**: MacOS 10.15.4 (Darwin WAHVE-WKS04.piholio 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64)
* **Subsystem**: ???

### What steps will reproduce the bug?

```sh
$ npm install -g --dry-run node@lts
+ node@12.18.1
added 2 packages in 0.247s
```

### How often does it reproduce? Is there a required condition?

Consistently outputs 12.18.1 every time

### What is the expected behavior?

```sh
+ node@12.18.2  # <-- 12.18.2 is the version listed on the site https://nodejs.org/en/
```

### What do you see instead?

```sh
+ node@12.18.1
```

### Additional information

Context - my team parses the dryrun output in our build to make sure that our project keeps up with LTS.
We're currently 1 version behind LTS - probably not a big deal but it could become a problem over time if this isn't fixed.

Note: Directed here from: https://github.com/nodejs/node/issues/34277

**Comment by aredridel** [comment]
Thanks! Fixed!

In general, I maintain `vX-lts` tags, since multiple branches can be lts at once, and tagging just 'lts' means you might get a major version without warning. That said `lts` should be maintained and is now pointing to 12.18.2.

**Comment by mlandisbqs** [comment]
...if there is a better way to programmatically pull the LTS version I am definitely all ears. I just assumed this was part of the build and deploy process for NodeJS / NPM :) Thanks for the fix.

**Comment by aredridel** [comment]
Heh, it's actually kinda manual on my part. I keep meaning to script it but never get around to it.

you can use the tag v12-lts if you want to pin to 12. Your case ("we want to test against whatever LTS is declared to be") might be the good reason to use the lts tag tho

**Comment by aredridel** [comment]
There's a json file on nodejs.org in the downloads directory that could be used for automation

**Comment by mlandisbqs** [comment]
Hmmm, I could not find that json file linked or in the source code for the page. My team also uses nvm to manage the node version switching and it looks like nvm has this command which could work well for us depending on how often nvm keeps it up to date:

```sh
nvm version-remote --lts
```

Found it here: https://github.com/nvm-sh/nvm/issues/1706

**Comment by aredridel** [comment]
The json file is at https://nodejs.org/dist/index.json

**Comment by aredridel** [comment]
And yeah, it's super hidden unless you directory hack your way there and realize that nodejs has old school FTP-site style parts.
