### ISSUE TITLE
Node 12.19.0

### ISSUE THREAD

**Issue by tabrindle** [aredridel/node-bin-gen#110]
Latest LTS is 12.19.0 - https://nodejs.org/en/download/releases/ but it's not available via https://www.npmjs.com/package/node

while attempting to install via yarn, got `error Couldn't find any versions for "node" that matches "12.19.0"` Looks like it was only published a week ago, so its understandable it's not there yet.

**Comment by aredridel** [comment]
I missed the release announcement! Fixed!

**Comment by tabrindle** [comment]
Thank you!
