### ISSUE TITLE
update or remove node-bin-setup

### ISSUE THREAD

**Issue by VadneyK** [aredridel/node-bin-gen#126]
It's 4 years old and causing many issues:

https://github.com/motdotla/dotenv/issues/540
https://github.com/aredridel/node-bin-gen/issues/124
https://github.com/aredridel/node-bin-gen/issues/60
https://github.com/aredridel/node-bin-gen/issues/59

please remove this as a dependency or update. very problematic.

**Comment by aredridel** [comment]
That's what makes this package work. Open a bug with the issue you're experiencing?
