### ISSUE TITLE
Cannot find module 'npm-linux-x64'!!!!!

### ISSUE THREAD

**Issue by UserIsDeid** [aredridel/node-bin-gen#135]
Help me
I get error ;
Cannot find module 'npm-linux-x64'

But i already installed npm-linux-x64

And i try to delete the node and install it again but the same problem.

**Comment by aredridel** [comment]
What triggers this error? When does it appear? How did you install it? Is it in your package.json, or installed with the CLI?  Is `npm-linux-x64` the correct package name? The packages this generates are `node-linux-x64` and similar.

**Comment by UserIsDeid** [comment]
> What triggers this error? When does it appear? How did you install it? Is it in your package.json, or installed with the CLI? Is `npm-linux-x64` the correct package name? The packages this generates are `node-linux-x64` and similar.

Thx i solve this problem.
