### ISSUE TITLE
Why do I get two different file sizes for node 16.13.1, depending on when I pulled from npm?

### ISSUE THREAD

**Issue by richgerrard** [aredridel/node-bin-gen#145]
I have one container that was created in early December, after the publish of node 16.13.1 to npm.
The second was created after December 18th, after the publish of node 17.3.0.

Inspecting my resulting containers and the files installed within shows two very different representations.  My scanner is failing the latest package on an unrecognized hash, as it no longer matches what was observed in early December.

Both should be node 16.13.1

Why/how has this changed?

```
$ docker run --user root ghcr.io/~/worker:2.8.3 ls -al /usr/bin/node
-rwxr-xr-x    1 root     root      39783144 Dec  1 21:29 /usr/bin/node
$ docker run --user root ghcr.io/~/worker:2.8.3 /usr/bin/node --version
v16.13.1

$ docker run --user root ghcr.io/~/worker:2.8.4 ls -al /usr/bin/node
-rwxr-xr-x    1 root     root      39791304 Dec 18 21:02 /usr/bin/node
$ docker run --user root ghcr.io/~/worker:2.8.4 /usr/bin/node --version
v16.13.1
```

**Comment by aredridel** [comment]
Good question! npm only allows them to be published once — did the architecture change?
