### ISSUE TITLE
No matching version found for node-darwin-x64@14.20.1

### ISSUE THREAD

**Issue by null0rUndefined** [aredridel/node-bin-gen#179]
It is not possible to use the node@14.20.1 package on Macs.

```
09:38:11  Error: Cannot find module 'node-darwin-x64/package.json'

09:38:11  npm ERR! code ETARGET
09:38:11  npm ERR! notarget No matching version found for node-darwin-x64@14.20.1.
09:38:11  npm ERR! notarget In most cases you or one of your dependencies are requesting
09:38:11  npm ERR! notarget a package version that doesn't exist.
```

[Nodejs version 14.20.1](https://nodejs.org/dist/v14.20.1) exists for the darwin-x64 and darwin-arm64 platforms, but an error occurs during installation.
It looks like these versions are not published to NPM.

Please publish node-darwin-x64@14.20.1 and node-darwin-arm64@14.20.1

**Comment by aredridel** [comment]
node-darwin-x64@14.20.1 has been published. Thanks for the heads up!

There is not a published release for darwin arm64 however.
