### ISSUE TITLE
License for generated packages?

### ISSUE THREAD

**Issue by mwiemer-microsoft** [aredridel/node-bin-gen#181]
Just curious, our project depends on node, which depends on node-win-x64. This seems to be the repo that generates node-win-x64, and this repo uses the ISC license. Would I be correct in assuming the generated packages have the same license?

**Comment by aredridel** [comment]
The generated packages are nodejs themselves, and trivial metadata. It's the node license as seen at https://github.com/nodejs/node/blob/main/LICENSE

**Comment by aredridel** [comment]
They do use [node-bin-setup](https://github.com/aredridel/node-bin-setup) to do the download, which is under the ISC license.
