### ISSUE TITLE
New lts version

### ISSUE THREAD

**Issue by GFdevelop** [aredridel/node-bin-gen#188]
Latest lts is v18

**Comment by aredridel** [comment]
Indeed it is and v18 has been published

**Comment by shaneog** [comment]
Will the `lts` tag stay on v16?

**Comment by aredridel** [comment]
Yeah. I want to do away with it entirely: vmajor-lts is the tag to use (v16-lts, v18-lts). Having a tag switch majors is not a useful semantic organization, so I'm going to stick with majors.
