### ISSUE TITLE
Could there be a more effective way to keep up the Node.js binary updating pace?

### ISSUE THREAD

**Issue by gemwuu** [aredridel/node-bin-gen#201]
Recently I found out that the Node.js binary has arleady released v16.19.1.
![image](https://user-images.githubusercontent.com/4635838/220272978-ed4975a9-8c20-4ca1-9280-bf817db0a495.png)

But the npm packages like node-linux-x64 only contains the v16.19.0.
![image](https://user-images.githubusercontent.com/4635838/220271714-707de2a7-a621-4c05-b6e8-54c54f679a48.png)

So, is there a better way to keep up the updating pace？Like, automatically publish all the platform packages right after the binaries were released?

**Comment by aredridel** [comment]
Yeah, I keep thinking i should automate it. I've just not done the work.

**Comment by gemwuu** [comment]
> Yeah, I keep thinking i should automate it. I've just not done the work.

I'll see if I can send you PR then

**Comment by aredridel** [comment]
And done!
