### ISSUE TITLE
No matching version found for node-bin-darwin-arm64@16.20.0

### ISSUE THREAD

**Issue by straub** [aredridel/node-bin-gen#212]
Hey there! Are we missing a package release for M1 Macs?
```
npm ERR! command sh -c node installArchSpecificPackage
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for node-bin-darwin-arm64@16.20.0.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
```
Please let me know if there's anything I can do to help!

**Comment by straub** [comment]
Looks like it has appeared now, thank you! (And/or sorry if I was merely being impatient 😄)

**Comment by aredridel** [comment]
Looks like some delays in the publication pipeline since Github laid off the npm registry team :/
