### ISSUE TITLE
Darwin-arm64 package for 16.11.1

### ISSUE THREAD

**Issue by stck** [aredridel/node-bin-gen#223]
Is it possible to add 16.11.1 package for darwin with arm64 (mb pro m1)? 
For now i see that minimal available version for this setup is 16.13.2 which is insufficient - since 16.12 has some buffer rework which is critical in my case (cannot migrate right now)

**Comment by aredridel** [comment]
Looking into it, it seems like I need to publish everything 16.0.0 to 16.13.0. I'll do that soon

**Comment by aredridel** [comment]
This has been published.

**Comment by stck** [comment]
Thank you a lot!
