### ISSUE TITLE
Support node v6.11.5

### ISSUE THREAD

**Issue by korneel** [aredridel/node-bin-gen#47]
Google Cloud Functions offers Node.js runtime, currently in version v6.11.5. I would like to use `npm -p node@6.11.5 -- npm install` to install my packages using the same version as the production runtime. But the `node` package doesn't have version 6.11.5. Can you add support for version 6.11.5?

**Comment by aredridel** [comment]
Whoops! I'd missed the node package for 6.11.5! Doing that now.

**Comment by aredridel** [comment]
Done!
