### ISSUE TITLE
plz more info on what it does maybe a complet example

### ISSUE THREAD

**Issue by frank-dspeed** [aredridel/node-bin-gen#5]
Plz more info what it does maybe a complet example

**Comment by aredridel** [comment]
Hehe. It's not a tool I expect anyone else to run unless they're intrigued by the concept. 

`node-bin-gen node 5.1.0` will make packages ready to publish in the current directory -- one called `node-bin` and one for each architecture/OS combo: `node-darwin-x64`. Those can then be installed (if published) and used as a `node` binary in your app.
