### ISSUE TITLE
Where's the latest current LTS: node@8.11.4 ?

### ISSUE THREAD

**Issue by elektronik2k5** [aredridel/node-bin-gen#52]
Hello! Thanks for such an amazing and useful project :bowing_man: 

```shell
yarn info node versions      
yarn info v1.9.4
[ '0.0.0',
# truncated versions...
'8.11.3',
# truncated versions...
'10.8.0' ]
```
[`node@8.11.4`](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#2018-08-15-version-8114-carbon-lts-rvagg) was released a week ago, but isn't published here. :cry: 

What happened? Can I help in any way?

**Comment by aredridel** [comment]
Ah, just gotta do it! Missed that one.


I should automate running this tbh

**Comment by aredridel** [comment]
Should be there now!

**Comment by elektronik2k5** [comment]
Can I help automate this process?

**Comment by aredridel** [comment]
Sure! Really, a script that reads what's on the registry vs the json file on nodejs.org and runs the thing would be sufficient. A cronjob after that would do the rest.

**Comment by elektronik2k5** [comment]
Cool, I'll start looking into this. So far found this abandoned(?) issue: https://github.com/nodejs/Release/issues/295
