### ISSUE TITLE
node installArchSpecificPackage fails

### ISSUE THREAD

**Issue by naz-mul** [aredridel/node-bin-gen#53]
11:18:21 > node@11.1.0 preinstall /var/lib/jenkins/jobs/eds-services-emv/workspace/eds-account-manager/node_modules/.staging/node-af0ef559
11:18:21 > node installArchSpecificPackage
11:18:21 
11:18:21 module.js:341
11:18:21     throw err;
11:18:21     ^
11:18:21 
11:18:21 Error: Cannot find module 'node-bin-setup'
11:18:21     at Function.Module._resolveFilename (module.js:339:15)
11:18:21     at Function.Module._load (module.js:290:25)
11:18:21     at Module.require (module.js:367:17)
11:18:21     at require (internal/module.js:20:19)
11:18:21     at Object.<anonymous> (/var/lib/jenkins/jobs/eds-services-emv/workspace/eds-account-manager/node_modules/.staging/node-af0ef559/installArchSpecificPackage.js:1:63)
11:18:21     at Module._compile (module.js:413:34)
11:18:21     at Object.Module._extensions..js (module.js:422:10)
11:18:21     at Module.load (module.js:357:32)
11:18:21     at Function.Module._load (module.js:314:12)
11:18:21     at Function.Module.runMain (module.js:447:10)

**Comment by aredridel** [comment]
What gives this error message?

**Comment by naz-mul** [comment]
@aredridel this happened during a build. I am assuming that's what you are asking me?

**Comment by rmg** [comment]
I get this when using npm@3.10.10 (shipped with node 6).

**Comment by aredridel** [comment]
Oh interesting. I'll have to see if I can replicate this

**Comment by noobling** [comment]
Any update on this issue? I can't use this package because of this problem... Could it be due to npm install running a different node version to install this? I am using a similar npm and node version.

**Comment by naz-mul** [comment]
@noobling one of the transient dependency was using a develop branch, rather than a specific version. I can't remember which library it was though. 

To fix it, I manually passed in a link to a release version in the package-lock/yarn-lock and ran yarn/npm install again.
