### ISSUE TITLE
node-win packages lack 0.x and 5.x

### ISSUE THREAD

**Issue by bisubus** [aredridel/node-bin-gen#61]
I discovered that https://www.npmjs.com/package/node-win-x64 and https://www.npmjs.com/package/node-win-x86 lack 0.x and 5.x versions. Exotic versions may be of little use, but it would be good to have legacy 0.10 and 0.12 at hand.

Is there a reason why they don't exist? Are there plans to fix this?

**Comment by aredridel** [comment]
nodejs.org does not publish windows binaries for the 0.x releases in a usable format if at all. There is no 5.x release; node versions go from 0.12 to 10, because of the io.js schism.
