### ISSUE TITLE
doesn't work with directory symlinks on windows

### ISSUE THREAD

**Issue by rogierschouten** [aredridel/node-bin-gen#85]
Ok so we have a bit of a weird setup: instead of a normal NPM install we have directory symlinks in our node_modules folders. Including the 'node' package then yields errors whenever we try to run 'npm run X'

The error (on windows) is "maximum setlocal recursion level reached".   Removing the 'node' package solves the issue, so I'm pretty sure that something in here isn't resistant to symlinks.

**Comment by aredridel** [comment]
Ooh, complex! I don't have an easy way to test this — a script or something that sets up the error case would be amazing so I can see if I can find a way around this.

**Comment by rogierschouten** [comment]
I know, it's not reproducible. Can't give you an easy error case so I thought I'd just give you a heads-up. Closing the issue for now.
