### ISSUE TITLE
Publish 13.7

### ISSUE THREAD

**Issue by Jamesernator** [aredridel/node-bin-gen#89]
Version 13.7.0 has been out for a week or so now and I've been wanting to be able to install it for portable scripts which need the new loader hooks.

There was [a comment](https://github.com/aredridel/node-bin-gen/issues/52#issuecomment-415640971) about automating the process but I'm not sure if that ever happened. Dunno if likely but it'd definitely be nice to include it as part of Node's official pipeline.

**Comment by aredridel** [comment]
Done! 

I'd happily hand this project off if node folks want to do it.
